name: macOS Tests (Swift)

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  workflow_dispatch:

jobs:
  macos-tests:
    name: Swift ${{ matrix.swift-version }} (macOS)
    runs-on: macos-12
    strategy:
      matrix:
        xcode-version:
          - '13.2.1'
          - '13.3.1'
        include:
          - swift-version: '5.5'
            xcode-version: '13.2.1'
          - swift-version: '5.6'
            xcode-version: '13.3.1'
    env:
      DEVELOPER_DIR: "/Applications/Xcode_${{ matrix.xcode-version }}.app/Contents/Developer"
    steps:
    - name: "⬇️ Checkout"
      uses: actions/checkout@v2
    - name: "🛠 Build and Run Tests"
      run: swift test --parallel
    - name: "🛠 Build Release"
      run: swift build --configuration release